title: Veselin Ivanov
tagline: Software Engineer
description: >-
  I'm a software engineer based in Copenhagen, Denmark. I specialize in platform
  engineering but I'm comfortable working across the stack.

exclude:
  - /.devenv/
  - /.direnv/
  - /Gemfile
  - /Gemfile.lock
  - /dev/
  - /flake.lock
  - /flake.nix
  - /gemset.nix
